users:
    root:
        password: ENC[AES256_GCM,data:csaGetup96n7lQcBDdKlJ6FGjoKfxQ5KOr31akvooTqz/6Z/wvsyAmaKWcGteZ6CZsGiM/hnAoCyFWk9IyyXA2fS1R8qmyWb6Djh0Hsh7sFk/2IpFs7ptaMFml9q/UOBWG0I,iv:CpUFU6UJVxNU0AJchjJ1Il+1D8WO8gifHjctUg8c/XQ=,tag:Jps3ghxgj1nUl1VxQLY/lg==,type:str]
    sweetdogs:
        password: ENC[AES256_GCM,data:9YEMQ7aG41Eg74r2xNfjTxpEXVAgrSLn7+G+is2dZqRJy75CN51bkWlR70xLOJ7TVrkdYKJWO6pq+M4959E4FsDJRYtJUYRKkmuATAYSEwN1n5YcrEsWigGnmR8Vex7mKbDG,iv:sBlTNjLON+S8ayizUxsIXwB/Dj67DX4Q7B72EiAW5ME=,tag:42gKUwqVPRtqejGQ2OifAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jtswyapws5vl8l37vkclr5cwmygmrulqcfsu6z44nvk4kxtwnfpqy74vr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZTBZdHovRWNpMDgzcnVM
            U2I1NlRVQjlPZmh3OE9EQVZNZytaVlYvOVNzCnRHYjF6WmlRamxjdEp4MWJQVjNr
            d211QnJtVE1jcTgvMWxidzZCTkgyTUUKLS0tICt5bU8vTVp4czFsczJ0aUJ2ZFhX
            eDdhbmdsbVp4RzlTcWdTYXc5M2R5OE0Kz+QdPusyvyt5UKV2gW0AK0HcEtU92iVn
            zXzAvoQIuqxL+K4brBWI5Ezdr9TQkd8WKQJuebziYbm6Ma4qbjd8mw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-27T18:12:54Z"
    mac: ENC[AES256_GCM,data:ktgnojlyhk+47NpkY+igwQOuBGVpmMofJtINfha5EnyDl+Y5dfPsVEIN78eea9Xcl+BNVc/Tk2LlX017Wm3GBCvahzoBcANCT8Z3edmiroeHynA8AaPn2gRlbLlfsZ2fRSzkW3qU79oYLJ2Nn4CxxDKj3AmwBnhp3JDOKIJyCuQ=,iv:AY9vB+5Ekivj5oz4BX+n9PacmGcSyq2YQgRZOq59We4=,tag:JnDtF5cvRepme8CpCH8hVw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
